### ISSUE TITLE
prop_checkOverwrittenExitCode8 fails with fgl-5.8.1.0

### ISSUE THREAD

**Issue by felixonmars** [koalaman/shellcheck#2677]
#### For bugs
- My shellcheck version (`shellcheck --version` or "online"): 0.9.0

With fgl upgraded from 5.8.0.0 to 5.8.1.0, the test "prop_checkOverwrittenExitCode8" now fails with an exception:
```
=== prop_checkOverwrittenExitCode8 from src/ShellCheck/Analytics.hs:4927 ===
*** Failed! Exception: '(Array.!): undefined array element' (after 1 test):
```

All other dependencies remained at the same versions during the test.

The only change in fgl seems to be https://github.com/haskell/fgl/commit/e26f7bb36642bc52183a382485ffe89dbe526569 and I don't really understand it.

**Comment by andreasabel** [comment]
As a consequence, shellcheck's tests have been disable on stackage:
- https://github.com/commercialhaskell/stackage/issues/6867

**Comment by athas** [comment]
I think (based on bisection) that this is actually the problematic commit: https://github.com/haskell/fgl/commit/f4c83ac53feb8cb98c5bfa0690a2e5ff89d1bffe

**Comment by koalaman** [comment]
The behavior of dominator searches have changed, and `fgl` now crashes in some cases. I've restricted the package bounds on Hackage and git, and filed https://github.com/haskell/fgl/issues/109

**Comment by athas** [comment]
I think this (and the related issues) should be fixed with the [fgl 5.8.1.1](https://hackage.haskell.org/package/fgl-5.8.1.1) I just uploaded to Hackage.  Apologies for the inconvenience.

**Comment by felixonmars** [comment]
Unfortunately, I am still getting exactly the same test failure with ShellCheck-0.9.0 with fgl-5.8.1.1 :(

**Comment by athas** [comment]
Shellcheck might still need the change in #2683; I'm not sure whether that was added separately.

**Comment by athas** [comment]
Shellcheck HEAD passes tests for me with fgl-5.8.1.1.  The fix from #2683 (or something equivalent) is in c05380d518056189412e12128a8906b8ca6f6717.

**Comment by mihaimaruseac** [comment]
This seems to be resolved on 0.10.0, just checked on Stackage
