### ISSUE TITLE
Fails to detect assignment post here doc start marker.

### ISSUE THREAD

**Issue by deryni** [koalaman/shellcheck#563]
This is probably related to #108 (and I feel like there was another heredoc related issue that I saw somewhat recently but couldn't find it now) but this snippet

    #!/bin/sh
    false <<EOF || { ret=$?; exit $ret; }
    EOF
    exit $ret

Reports [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154) on the usage of `$ret` in the `exit` command on line 2 but does *not* report it on line 4.

Probably relatedly, shellcheck does *not* report [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086) on line 2 but *does* report it on line 4.

**Comment by knirch** [comment]
Probably same issue, but a more common pattern;

```bash
file="foo bar"
cat <<EOF >> $file
foobar
EOF
```

**Comment by koalaman** [comment]
Fixed in 2f0ae44

**Comment by miken32** [comment]
This is still an issue if there's no spacing. E.g. `cat <<EOF>file`
